### ISSUE TITLE
Using Blob for WebWorker

### ISSUE THREAD

**Issue by Weedshaker** [satya164/web-worker-proxy#1]
Hi,

I like this repo. Good idea using es6 Proxy with WebWorkers this way. Though, I just wanted to hint you with making the WebWorker through a Blob, this way you may can make it easier for the user to setup the WebWorker. Something similar to: https://github.com/Weedshaker/Proxify/blob/master/JavaScript/Classes/Helper/Misc/WebWorkers.js

Cheers

**Comment by satya164** [comment]
Thanks! The library just needs a worker instance, it can be created from a URL or a blob, it won't matter :)

I'm not a big fan of creating web workers from blobs though, because debugging can be hard, you can't recognize the web worker from the blob url and source maps won't work, also some browsers don't support certain features inside blob web workers, for example, IE or Edge don't support IndexedDB inside web workers.

**Comment by Weedshaker** [comment]
Good point... it just flashed through my mind... due to the work i did at: https://weedshaker.github.io/Proxify/#WebWorkers and thought this might be useful for less config. I am going to dig a bit more into your library. Its nice to see people using es6 Proxy. I believe its far more powerful than what it has been used for so far...

**Comment by satya164** [comment]
Totally agree.
